---
- name: Adding JVM file
  template:
    src: jvm.options.j2
    dest: "/home/ubuntu/opensearch-2.11.0/config/jvm.options"
    mode: 0600
    force: true
  become: yes
  become_user: root
  
- name: Generate a root certificate
  shell: "openssl genrsa -out root-ca-key.pem 2048"
  args:
    chdir: /home/ubuntu/opensearch-2.11.0/config/

- name: Create a root certificate
  shell: "openssl req -new -x509 -sha256 -key root-ca-key.pem -subj '/C=CA/ST=ONTARIO/L=TORONTO/O=ORG/OU=UNIT/CN=ROOT' -out root-ca.pem -days 730"
  args:
   chdir: /home/ubuntu/opensearch-2.11.0/config/

- name: Create a private key for the admin certificate
  shell: "openssl genrsa -out admin-key-temp.pem 2048"
  args:
    chdir: /home/ubuntu/opensearch-2.11.0/config/

- name: Convert the private key to PKCS#8
  shell: "openssl pkcs8 -inform PEM -outform PEM -in admin-key-temp.pem -topk8 -nocrypt -v1 PBE-SHA1-3DES -out admin-key.pem"
  args:
    chdir: /home/ubuntu/opensearch-2.11.0/config/

- name: Create an admin certificate signing request
  shell: "openssl req -new -key admin-key.pem -subj '/C=CA/ST=ONTARIO/L=TORONTO/O=ORG/OU=UNIT/CN=A' -out admin.csr"
  args:
    chdir: /home/ubuntu/opensearch-2.11.0/config/

- name: Sign the admin certificate with the root certificate
  shell: "openssl x509 -req -in admin.csr -CA root-ca.pem -CAkey root-ca-key.pem -CAcreateserial -sha256 -out admin.pem -days 730"
  args:
    chdir: /home/ubuntu/opensearch-2.11.0/config/

- name: Create a private key for the node certificate
  shell: "openssl genrsa -out node1-key-temp.pem 2048"
  args:
    chdir: /home/ubuntu/opensearch-2.11.0/config/

- name: Convert the private key to PKCS#8 for the node certificate
  shell: "openssl pkcs8 -inform PEM -outform PEM -in node1-key-temp.pem -topk8 -nocrypt -v1 PBE-SHA1-3DES -out node1-key.pem"
  args:
    chdir: /home/ubuntu/opensearch-2.11.0/config/

- name: Create a node certificate signing request
  shell: "openssl req -new -key node1-key.pem -subj '/C=CA/ST=ONTARIO/L=TORONTO/O=ORG/OU=UNIT/CN=node1.dns.a-record' -out node1.csr"
  args:
    chdir: /home/ubuntu/opensearch-2.11.0/config/

- name: Create an extension file for the node certificate
  shell: "echo 'subjectAltName=DNS:node1.dns.a-record' > node1.ext"
  args:
    chdir: /home/ubuntu/opensearch-2.11.0/config/

- name: Sign the node certificate with the root certificate
  shell: "openssl x509 -req -in node1.csr -CA root-ca.pem -CAkey root-ca-key.pem -CAcreateserial -sha256 -out node1.pem -days 730 -extfile node1.ext"
  args:
    chdir: /home/ubuntu/opensearch-2.11.0/config/

- name: Remove temporary files
  shell: "rm *temp.pem *csr *ext"
  args:
    chdir: /home/ubuntu/opensearch-2.11.0/config/

- name: change permission
  shell: "chown ubuntu:ubuntu admin-key.pem admin.pem node1-key.pem node1.pem root-ca-key.pem root-ca.pem root-ca.srl"
  args:
    chdir: /home/ubuntu/opensearch-2.11.0/config/
