---
- name: Installll-OpenSearch.yml
  include_tasks: Install-Opensearch.yml
  
- name: Adding certificates to OpenSearch.yml
  include_tasks: opensearch.yml

- name: Adding JVM file
  template:
    src: jvm.options.j2
    dest: "/home/ubuntu/opensearch-2.11.0/config/jvm.options"
    mode: 0600
    force: true
  become: yes
  become_user: root

#Configure TLS
- name: Set up TLS certificates for OpenSearch
  include_tasks: configure_tls.yml

- name: hash.sh password generation
  include_tasks: user_management.yml

- name: Initialize Opensearch
  include_tasks: initialize_opensearch.yml

- name: Initialize Opensearch-dashboards
  include_tasks: opensearch_dashboard.yml






  
