---
- name: Installll-OpenSearch.yml
  include_tasks: Install-Opensearch.yml
  
- name: Adding certificates to OpenSearch.yml
  include_tasks: opensearch.yml

- name: Set up TLS certificates for OpenSearch
  include_tasks: configure_tls.yml

- name: hash.sh password generation
  include_tasks: user_management.yml

- name: Initialize Opensearch
  include_tasks: initialize_opensearch.yml

- name: Initialize Opensearch-dashboards
  include_tasks: opensearch_dashboard.yml






  
